<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CS0-37" name="cs265.CS265_Lab1Test" tests="6" failures="3" timestamp="16 Feb 2018 14:20:53 GMT" time="0.029" errors="0">
  <testcase name="method1_test1" time="0.020" classname="cs265.CS265_Lab1Test"/>
  <testcase name="method1_test3" time="0.001" classname="cs265.CS265_Lab1Test">
    <failure type="java.lang.AssertionError" message="expected:&lt;-55&gt; but was:&lt;-1&gt;">
      <![CDATA[java.lang.AssertionError: expected:<-55> but was:<-1>at org.testng.AssertJUnit.fail(AssertJUnit.java:59)at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)at cs265.CS265_Lab1Test.method1_test3(CS265_Lab1Test.java:21)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- method1_test3 -->
  <testcase name="method1_test4" time="0.001" classname="cs265.CS265_Lab1Test"/>
  <testcase name="method1_test6" time="0.004" classname="cs265.CS265_Lab1Test">
    <failure type="java.lang.AssertionError" message="expected:&lt;12&gt; but was:&lt;15&gt;">
      <![CDATA[java.lang.AssertionError: expected:<12> but was:<15>at org.testng.AssertJUnit.fail(AssertJUnit.java:59)at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)at cs265.CS265_Lab1Test.method1_test6(CS265_Lab1Test.java:36)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- method1_test6 -->
  <testcase name="method1_test2" time="0.001" classname="cs265.CS265_Lab1Test"/>
  <testcase name="method1_test5" time="0.002" classname="cs265.CS265_Lab1Test">
    <failure type="java.lang.AssertionError" message="expected:&lt;81&gt; but was:&lt;-1&gt;">
      <![CDATA[java.lang.AssertionError: expected:<81> but was:<-1>at org.testng.AssertJUnit.fail(AssertJUnit.java:59)at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)at cs265.CS265_Lab1Test.method1_test5(CS265_Lab1Test.java:31)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- method1_test5 -->
</testsuite> <!-- cs265.CS265_Lab1Test -->
